class CompletedProjectItemModel {
  CompletedProjectItemModel(this.id, this.imgPaths, this.title, this.budget,
      this.timespan, this.status, this.size, this.location);

  final int id;
  final List<String> imgPaths;
  final String title;
  final String budget;
  final String timespan;
  final String status;
  final String size;
  final String location;
}

List<CompletedProjectItemModel> completedProjects = [
  CompletedProjectItemModel(
    0,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_224805047.MP.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_224807728.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_224821148.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_224821148.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_224842714.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_224846319.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_224846319.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_224956809.MP.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_225007011.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_225013641.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_225021685.MP.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_225034042.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBlackAccentBathroom%2FPXL_20240204_225047676.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'Black Accent Bathroom',
    '\$7000',
    'January 2024',
    'Completed',
    'Small',
    'Miami, FL',
  ),
  CompletedProjectItemModel(
    1,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FWhiteAccentBathroom%2F1.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FWhiteAccentBathroom%2F2.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FWhiteAccentBathroom%2F3.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FWhiteAccentBathroom%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FWhiteAccentBathroom%2F5.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FWhiteAccentBathroom%2F6.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FWhiteAccentBathroom%2F7.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FWhiteAccentBathroom%2F8.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FWhiteAccentBathroom%2F9.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FWhiteAccentBathroom%2F99.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'White Modern Bathroom',
    '\$6000',
    'October 2023',
    'Completed',
    'Small',
    'Miami, FL',
  ),
  CompletedProjectItemModel(
    2,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FStairWithLights%2F1.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FStairWithLights%2F2.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FStairWithLights%2F3.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FStairWithLights%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FStairWithLights%2F5.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FStairWithLights%2F6.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FStairWithLights%2F7.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FStairWithLights%2F8.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'Sair with Lights',
    '\$1400',
    'February 2024',
    'Completed',
    'Small',
    'Miami, FL',
  ),
  CompletedProjectItemModel(
    3,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FFloor%20and%20Baseboard%2F1.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FFloor%20and%20Baseboard%2F2.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FFloor%20and%20Baseboard%2F3.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FFloor%20and%20Baseboard%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FFloor%20and%20Baseboard%2F5.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'Floor and Baseboards',
    '\$2000',
    'October 2023',
    'Completed',
    'Small',
    'Miami, FL',
  ),
  CompletedProjectItemModel(
    4,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F1.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F2.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F3.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F5.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F6.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F7.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F8.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F9.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F99.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FModernWithBathroom2%2F999.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'Modern White Bathroom 2',
    'Confidential',
    'date',
    'Completed',
    'Small',
    'Miami, FL',
  ),
  CompletedProjectItemModel(
    5,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FKitchenSplashandFloor%2F1.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FKitchenSplashandFloor%2F2.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FKitchenSplashandFloor%2F3.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FKitchenSplashandFloor%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FKitchenSplashandFloor%2F5.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FKitchenSplashandFloor%2F6.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FKitchenSplashandFloor%2F7.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FKitchenSplashandFloor%2F8.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FKitchenSplashandFloor%2F9.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'Kitchen Splash & Floor',
    'Confidential',
    'date',
    'Completed',
    'Medium',
    'Miami, FL',
  ),
  CompletedProjectItemModel(
    6,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FNicePorch%2F1.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FNicePorch%2F2.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FNicePorch%2F3.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FNicePorch%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FNicePorch%2F5.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FNicePorch%2F6.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FNicePorch%2F7.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'Nice Porch',
    'Confidential',
    'date',
    'Completed',
    'Medium',
    'Miami, FL',
  ),
  CompletedProjectItemModel(
    7,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FTileFloor%2F1.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FTileFloor%2F3.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FTileFloor%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FTileFloor%2F5.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FTileFloor%2F6.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FTileFloor%2F7.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FTileFloor%2F8.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FTileFloor%2F9.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FTileFloor%2F9999.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'Tile Floor',
    'Confidential',
    'date',
    'Completed',
    'Medium',
    'Miami, FL',
  ),
  CompletedProjectItemModel(
    8,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F1.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F2.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F3.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F6.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F7.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F8.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'Backyard Walkway',
    'Confidential',
    'date',
    'Completed',
    'Small',
    'Miami, FL',
  ),
  CompletedProjectItemModel(
    9,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F1.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F2.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F3.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F6.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F7.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardWalkway%2F8.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'Backyard Walkway',
    'Confidential',
    'date',
    'Completed',
    'Small',
    'Miami, FL',
  ),
  CompletedProjectItemModel(
    10,
    [
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardPorch%2F1.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardPorch%2F12.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardPorch%2F2.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardPorch%2F3.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardPorch%2F4.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardPorch%2F5.jpg?alt=media&format&fit=crop&w=1740&q=80',
      'https://firebasestorage.googleapis.com/v0/b/roly-website.appspot.com/o/ProjectPhotos%2FBackyardPorch%2F6.jpg?alt=media&format&fit=crop&w=1740&q=80',
    ],
    'Backyard Porch',
    'Confidential',
    'date',
    'Completed',
    'Medium',
    'Miami, FL',
  ),
];
